### ISSUE TITLE
Incompatible with NBGV

### ISSUE THREAD

**Issue by gfs** [FuLagann/csharp-docs-generator#16]
If you have a project that uses [NBGV](https://github.com/dotnet/Nerdbank.GitVersioning) for versioning you can't just "dotnet build" it with this tool.

Are you working on a detached head?

## Workaround
Add `nbgv set-version blah` to explicitly set the version directly before building.

## Output
```
C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.1.91\build\Nerdbank.GitVersioning.targets(71,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [d:\a\OAT\OAT\OAT\OAT.csproj]
C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.1.91\build\Nerdbank.GitVersioning.targets(71,5): error MSB4018: System.InvalidOperationException: Unable to get version from commit: 7a388a3e978750c2fd2046987756b5eb03f59fe9 [d:\a\OAT\OAT\OAT\OAT.csproj]
C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.1.91\build\Nerdbank.GitVersioning.targets(71,5): error MSB4018:  ---> System.NullReferenceException: Object reference not set to an instance of an object. [d:\a\OAT\OAT\OAT\OAT.csproj]
C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.1.91\build\Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) [d:\a\OAT\OAT\OAT\OAT.csproj]
C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.1.91\build\Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.Proxy.git_commit_tree_id(ObjectHandle obj) [d:\a\OAT\OAT\OAT\OAT.csproj]
```

**Comment by FuLagann** [comment]
The input `build-tasks` is an array of commands separated by commas meant for the user to configure and build everything needed prior to generating documentation. This is to accommodate as many project setups as possible. Thus you can use:

```yml
build-tasks:
  nbgv set-version 1.0,
  dotnet build
```

From the looks of your repository, you seem to have added it. As for the detached head part, I'm not entirely sure what you mean but the action works on it and commits it to the current branch that it got pushed to.

**Comment by gfs** [comment]
Thanks.

I know there is a workaround to force the version number, but that doesn't really solve the problem here as the resulting version number is the incorrect forced version (which flows through).

The normal build for this project is actually `dotnet build` - no version setting, the version is calculated automatically from the commit height by nbgv during the build process.
