### ISSUE TITLE
Error in README yaml example

### ISSUE THREAD

**Issue by Morasiu** [FuLagann/csharp-docs-generator#17]
Using this gave me an error:

```
      - name: Generate Documentation
        uses: FuLagann/csharp-docs-generator@v1
```

but this is working. Notice the "v.1.0"

```
      - name: C# Documentation Generator
        uses: FuLagann/csharp-docs-generator@v1.0
```

**Comment by FuLagann** [comment]
This is a big oversight! Thanks for catching it! Accepted the pull request that updates this and the readme is updated.
