### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Morasiu** [FuLagann/csharp-docs-generator#21]
Great tool. But I lack information in README.

What should I do with the site after it's generated?

Like should I host it on Github Pages? If yes then how can I do it? Just a simple tutorial would be ok 👍

**Comment by FuLagann** [comment]
I have gotten tips to add a getting started, I thought it was intuitive enough. I'll be adding a section in the readme with more details in the wiki. I'm working on adding this

**Comment by FuLagann** [comment]
Getting Started has been added to readme with newest update (PR #27)
