### ISSUE TITLE
Missing index.html

### ISSUE THREAD

**Issue by Morasiu** [FuLagann/csharp-docs-generator#22]
There is no `index.html`  in generated files. 

Is it that intentional?

**Comment by FuLagann** [comment]
Partially yes, it was intended to be linked from other html files outside of the API. But it seems like it would cause more problems than anything, I will be working on adding an automated index.html that links to all the namespaces with probably some description of the library/product next.

**Comment by Morasiu** [comment]
Great. I'm really looking forward to it 👍

**Comment by FuLagann** [comment]
The latest update includes generating index.html (PR #27)
